services:
  api:
    build: .
    container_name: shortly-api

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql+psycopg://shortly:shortly_password@postgres:5432/shortly
      REDIS_URL: redis://redis:6379/0

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: shortly-postgres

    environment:
      POSTGRES_USER: shortly
      POSTGRES_PASSWORD: shortly_password
      POSTGRES_DB: shortly

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortly -d shortly"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: shortly-redis

    ports:
      - "6379:6379"

volumes:
  postgres_data: